PustokImagesUploadTask/Models/Book.cs
using PustokImagesUploadTask.Base;
using System.ComponentModel.DataAnnotations.Schema;

namespace PustokImagesUploadTask.Models
{
    public class Book : BaseEntity
    {
        public int CategoryId { get; set; }
        public int AuthorId { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public double SalePrice { get; set; }
        public double DiscountPrice { get; set; }
        public double CostPrice { get; set; }
        public bool IsAvalible { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsNew { get; set; }

        public Category? Category { get; set; }
        public Author? Author { get; set; }
        public List<OrderItem>? OrderItems { get; set; }
        public List<BookImage>? BookImages { get; set; }
        [NotMapped]
        public List<IFormFile>? ImageFiles { get; set; }
        [NotMapped]
        public IFormFile? PosterImage { get; set; }
        [NotMapped]
        public IFormFile? HoverImage { get; set; }

        [NotMapped]
        public List<int>? BookImageIds { get; set; }

        [NotMapped]
        public int? BookPosterImgId{ get; set; }

        [NotMapped]
        public int? BookHoverImgId{ get; set; }

    }
}

PustokImagesUploadTask/Areas/Admin/Controllers/BookController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PustokImagesUploadTask.Helpers;
using PustokImagesUploadTask.Models;
using PustokImagesUploadTask.ViewModels;

namespace PustokImagesUploadTask.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BookController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly IWebHostEnvironment _env;

        public BookController(AppDbContext context, UserManager<AppUser> userManager , IWebHostEnvironment env)
        {
            _context = context;
            _userManager = userManager;
            _env = env;
        }
        public IActionResult Index()
        {
            return View(_context.Books.ToList());
        }
        public IActionResult Create()
        {
            ViewBag.Authors = _context.Authors.ToList();
            ViewBag.Categories = _context.Categories.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Create(Book book)
        {
            ViewBag.Authors = _context.Authors.ToList();
            ViewBag.Categories = _context.Categories.ToList();

            if (book.ImageFiles == null) ModelState.AddModelError("ImageFiles", "Required");
            if (book.PosterImage == null) ModelState.AddModelError("PosterImage", "Required");
            if (book.HoverImage == null) ModelState.AddModelError("HoverImage", "Required");

            if (!ModelState.IsValid) return View(book);

            foreach (IFormFile formFile in book.ImageFiles)
            {
                if (!formFile.CheckFileLength(1048576))
                {
                    ModelState.AddModelError("ImageFiles", "Please , upload less than 1Mb");
                    return View();
                }
                if (!formFile.CheckFileType())
                {
                    ModelState.AddModelError("ImageFiles", "Please , upload only image file (jpeg or png) ");
                    return View();
                }


                BookImage bookImage = new BookImage()
                {
                    Book = book,
                    Name = formFile.SaveFile(_env.WebRootPath, "uploads/books"),
                    IsPoster = null
                };

                _context.BookImages.Add(bookImage);
            }

            if (!book.PosterImage.CheckFileLength(1048576))
            {
                ModelState.AddModelError("PosterImage", "Please , upload less than 1Mb");
                return View();
            }
            if (!book.PosterImage.CheckFileType())
            {
                ModelState.AddModelError("PosterImage", "Please , upload only image file (jpeg or png) ");
                return View();
            }
            BookImage bookImage1 = new BookImage()
            {
                Book = book,
                Name = book.PosterImage.SaveFile(_env.WebRootPath, "uploads/books"),
                IsPoster = true
            };
            _context.BookImages.Add(bookImage1);

            if (!book.HoverImage.CheckFileLength(1048576))
            {
                ModelState.AddModelError("HoverImage", "Please , upload less than 1Mb");
                return View();
            }
            if (!book.HoverImage.CheckFileType())
            {
                ModelState.AddModelError("HoverImage", "Please , upload only image file (jpeg or png) ");
                return View();
            }
            BookImage bookImage2 = new BookImage()
            {
                Book = book,
                Name = book.HoverImage.SaveFile(_env.WebRootPath, "uploads/books"),
                IsPoster = false
            };
            _context.BookImages.Add(bookImage2);



            _context.Books.Add(book);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        public IActionResult Update(int id)
        {
            ViewBag.Authors = _context.Authors.ToList();
            ViewBag.Categories = _context.Categories.ToList();
            Book book = _context.Books.Include(x => x.BookImages).Include(x => x.Author).Include(x => x.Category).FirstOrDefault(x => x.Id == id);
            if (book is null) return View("Error");
            if (!ModelState.IsValid) return View(book);
            return View(book);
        }
        [HttpPost]
        public IActionResult Update(Book book)
        {

            Book exist1 = _context.Books.Include(x => x.BookImages).FirstOrDefault(x => x.Id == book.Id);
            if (exist1 is null) return View("Error");

            if (book.BookImageIds is not null)
            {
                List<BookImage> images = exist1.BookImages.Where(bimg => !book.BookImageIds.Contains(bimg.Id) & bimg.IsPoster == null).ToList();
                foreach (var item in images)
                {
                    if (System.IO.File.Exists(Path.Combine(_env.WebRootPath, "uploads/books", item.Name)))
                        System.IO.File.Delete(Path.Combine(_env.WebRootPath, "uploads/books", item.Name));
                }
                exist1.BookImages.RemoveAll(bimg => !book.BookImageIds.Contains(bimg.Id) & bimg.IsPoster == null);
            }
            else
            {
                List<BookImage> images = exist1.BookImages.Where(bimg => bimg.IsPoster == null).ToList();
                foreach (var item in images)
                {
                    if (System.IO.File.Exists(Path.Combine(_env.WebRootPath, "uploads/books", item.Name)))
                        System.IO.File.Delete(Path.Combine(_env.WebRootPath, "uploads/books", item.Name));
                }
                exist1.BookImages.RemoveAll(bimg => bimg.IsPoster == null);
            }

            if (book.BookHoverImgId is null)
            {
                BookImage? bookImage = exist1.BookImages.FirstOrDefault(x => x.IsPoster == false);
                if (bookImage != null)
                {
                    if (System.IO.File.Exists(Path.Combine(_env.WebRootPath, "uploads/books", bookImage.Name)))
                        System.IO.File.Delete(Path.Combine(_env.WebRootPath, "uploads/books", bookImage.Name));
                    exist1.BookImages.Remove(exist1.BookImages?.FirstOrDefault(x => x.IsPoster == false));
                }
            }
            if (book.BookPosterImgId is null)
            {
                BookImage? bookImage = exist1.BookImages.FirstOrDefault(x => x.IsPoster == true);
                if (bookImage != null)
                {
                    if (System.IO.File.Exists(Path.Combine(_env.WebRootPath, "uploads/books", bookImage.Name)))
                        System.IO.File.Delete(Path.Combine(_env.WebRootPath, "uploads/books", bookImage.Name));
                    exist1.BookImages.Remove(exist1.BookImages?.FirstOrDefault(x => x.IsPoster == true));
                }
            }



            if (book.ImageFiles is not null)
            {
                List<BookImage> oldbookimages = _context.BookImages.Where(x => x.BookId == book.Id).Where(x => x.IsPoster == null).ToList();

                foreach (IFormFile formFile in book.ImageFiles)
                {
                    if (!formFile.CheckFileLength(1024576)) ModelState.AddModelError("ImageFiles", "Please, upload less than 1 Mb");
                    if (!formFile.CheckFileType()) ModelState.AddModelError("ImageFiles", "Please, upload only image (jpeg,png)");

                    BookImage bookImage = new BookImage()
                    {
                        BookId = book.Id,
                        Name = formFile.SaveFile(_env.WebRootPath, "uploads/books"),
                        IsPoster = null
                    };
                    _context.BookImages.Add(bookImage);
                }
            }
            if (book.HoverImage is not null)
            {

                BookImage bookImage2 = new BookImage()
                {
                    Book = exist1,
                    Name = book.HoverImage.SaveFile(_env.WebRootPath, "uploads/books"),
                    IsPoster = false
                };
                _context.BookImages.Add(bookImage2);
            }

            if (book.PosterImage is not null)
            {

                BookImage bookImage2 = new BookImage()
                {
                    Book = exist1,
                    Name = book.PosterImage.SaveFile(_env.WebRootPath, "uploads/books"),
                    IsPoster = true
                };
                _context.BookImages.Add(bookImage2);
            }


            if (!ModelState.IsValid) return View();

            Book exist = _context.Books.FirstOrDefault(x => x.Id == book.Id);

            exist.Name = book.Name;
            exist.IsFeatured = book.IsFeatured;
            exist.IsNew = book.IsNew;
            exist.AuthorId = book.AuthorId;
            exist.CategoryId = book.CategoryId;
            exist.Description = book.Description;
            exist.DiscountPrice = book.DiscountPrice;
            exist.CostPrice = book.CostPrice;
            exist.SalePrice = book.SalePrice;
            exist.Code = book.Code;
            exist.IsAvalible = book.IsAvalible;

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            Book book = _context.Books.Find(id);
            if (book is null) return NotFound();

            foreach (BookImage image in _context.BookImages.Where(x => x.BookId == id))
            {
                if (System.IO.File.Exists(Path.Combine(_env.WebRootPath, "uploads/books", image.Name)))
                    System.IO.File.Delete(Path.Combine(_env.WebRootPath, "uploads/books", image.Name));
            }

            _context.Books.Remove(book);
            _context.SaveChanges();

            return Ok();

        }

PustokImagesUploadTask/Areas/Admin/Views/Book/Create.cshtml
@model Book


<div class="container-fluid">
    <h1 style="text-align:center">Create Book</h1>

    <form method="post" asp-action="create" enctype="multipart/form-data">
        <div class="row align-items-center">


            <div class="mb-3 col-md-4">
                <label asp-for="Name" class="form-label">Name</label>
                <input asp-for="Name" class="form-control" placeholder="Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="CostPrice" class="form-label">Costprice</label>
                <input asp-for="CostPrice" class="form-control" placeholder="Costprice">
                <span asp-validation-for="CostPrice" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="SalePrice" class="form-label">SalePrice</label>
                <input asp-for="SalePrice" class="form-control" placeholder="SalePrice">
                <span asp-validation-for="SalePrice" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="DiscountPrice" class="form-label">DiscountPrice</label>
                <input asp-for="DiscountPrice" class="form-control" placeholder="DiscountPrice">
                <span asp-validation-for="DiscountPrice" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="Code" class="form-label">Code</label>
                <input asp-for="Code" class="form-control" placeholder="Code">
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="Description" class="form-label">Description</label>
                <textarea class="form-control" asp-for="Description" rows="5" placeholder="Description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="AuthorId">Authors</label>
                <select asp-for="AuthorId" asp-items="@(new SelectList(ViewBag.Authors,"Id","Name"))">
                </select>
                <span asp-validation-for="AuthorId" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="CategoryId">Categories</label>
                <select asp-for="CategoryId" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))">
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="col-4"></div>
            <div class="mb-3 col-md-4 pt-3">
                <label asp-for="ImageFiles" class="form-label">Image</label>
                <input asp-for="ImageFiles" class="form-control" placeholder="Image">
                <span asp-validation-for="ImageFiles" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-4 pt-3">
                <label asp-for="PosterImage" class="form-label">PosterImage</label>
                <input asp-for="PosterImage" class="form-control" placeholder="PosterImage">
                <span asp-validation-for="PosterImage" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-4 pt-3">
                <label asp-for="HoverImage" class="form-label">HoverImage</label>
                <input asp-for="HoverImage" class="form-control" placeholder="HoverImage">
                <span asp-validation-for="HoverImage" class="text-danger"></span>
            </div>
        </div>

        <div class="row">
        <div class="form-check col-md-3 pb-3" style="padding-top: 16px;">
            <input class="form-check-input" type="checkbox" asp-for="IsAvalible" checked>
            <label class="form-check-label" asp-for="IsAvalible">
                IsAvalible
            </label>
        </div>
        <div class="form-check col-md-3 pb-3" style="padding-top: 16px;">
            <input class="form-check-input" type="checkbox" asp-for="IsFeatured" checked>
            <label class="form-check-label" asp-for="IsFeatured">
                    IsFeatured
            </label>
        </div>
        <div class="form-check col-md-3 pb-3" style="padding-top: 16px;">
            <input class="form-check-input" type="checkbox" asp-for="IsNew" checked>
                <label class="form-check-label" asp-for="IsNew">
                    IsNew
            </label>
        </div>

        </div>


        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

PustokImagesUploadTask/Areas/Admin/Views/Book/Index.cshtml
@model List<Book>
@{
    int counter = 0;
}

<div class="container">

    <div class="container">
        <div>
            <h1 style="text-align:center">Books</h1>
        </div>
    </div>

    <div class="container-fluid pt-3">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">SalePrice</th>
                    <th scope="col">Discount</th>
                    
                    <th scope="col"> <a asp-controller="Book" asp-action="create" class="btn btn-primary">Create</a> </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Book sl in Model)
                {
                    counter++;
                    <tr>
                        <th scope="row">@counter</th>
                        <td>@sl.Id</td>
                        <td>@sl.Name</td>
                        <td>@sl.SalePrice</td>
                        <td>@sl.DiscountPrice</td>
                        
                        <td>
                            <a asp-controller="Book" asp-action="update" asp-route-id="@sl.Id" a class="btn btn-success">Update</a>
                            <a asp-controller="Book" asp-action="delete" asp-route-id="@sl.Id" class="btn btn-danger deletebutton">Delete</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

PustokImagesUploadTask/Areas/Admin/Views/Book/Update.cshtml
@model Book


<div class="container-fluid">
    <h1 style="text-align:center">Update Book</h1>

    <form method="post" asp-action="update" enctype="multipart/form-data">
        <div class="row align-items-center">


            <div class="mb-3 col-md-3">
                <label asp-for="Name" class="form-label">Name</label>
                <input asp-for="Name" class="form-control" placeholder="Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-3">
                <label asp-for="Code" class="form-label">Code</label>
                <input asp-for="Code" class="form-control" placeholder="Code">
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-2">
                <label asp-for="CostPrice" class="form-label">Costprice</label>
                <input asp-for="CostPrice" class="form-control" placeholder="Costprice">
                <span asp-validation-for="CostPrice" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-2">
                <label asp-for="SalePrice" class="form-label">SalePrice</label>
                <input asp-for="SalePrice" class="form-control" placeholder="SalePrice">
                <span asp-validation-for="SalePrice" class="text-danger"></span>
            </div>
            <div class="mb-3 col-md-2">
                <label asp-for="DiscountPrice" class="form-label">DiscountPrice</label>
                <input asp-for="DiscountPrice" class="form-control" placeholder="DiscountPrice">
                <span asp-validation-for="DiscountPrice" class="text-danger"></span>
            </div>

            <div class="mb-3 col-md-4">
                <label asp-for="Description" class="form-label">Description</label>
                <textarea class="form-control" asp-for="Description" rows="5" placeholder="Description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>


            <div class="mb-3 col-md-4 pt-3">
                <label asp-for="PosterImage" class="form-label">PosterImage</label>
                <input asp-for="PosterImage" class="form-control" placeholder="PosterImage">
                <span asp-validation-for="PosterImage" class="text-danger"></span>
                <div style="position:relative">
                    @Html.Raw((Model.BookImages?.FirstOrDefault(x=>x.IsPoster == true) is not null) ?
                    $"<img class=\"pt-3\" width=\"200px\" src=\"/uploads/books/{@Model.BookImages?.FirstOrDefault(x=>x.IsPoster==true)?.Name}\" />" : "")
                    <span class="x-button" style="position:absolute; right: 210px;top: 20px;cursor: pointer;color: red;font-size:@((Model.BookImages?.FirstOrDefault(x=>x.IsPoster == true) is not null) ? "20px" : "0px") ; font-weight: bold;">X</span>
                    <input type="hidden" name="BookPosterImgId" value="@Model.BookImages?.FirstOrDefault(x=>x.IsPoster==true)?.Id">
                </div>

            </div>
            <div class="mb-3 col-md-4 pt-3">
                <label asp-for="HoverImage" class="form-label">HoverImage</label>
                <input asp-for="HoverImage" class="form-control" placeholder="HoverImage">
                <span asp-validation-for="HoverImage" class="text-danger"></span>
                <div style="position:relative">
                 @Html.Raw((Model.BookImages?.FirstOrDefault(x=>x.IsPoster == false) is not null) ? 
                    $"<img class=\"pt-3\" width=\"200px\" src=\"/uploads/books/{@Model.BookImages?.FirstOrDefault(x=>x.IsPoster==false)?.Name}\" />" : "")
                    <span class="x-button" style="position:absolute; right: 210px;top: 20px;cursor: pointer;color: red;font-size:@((Model.BookImages?.FirstOrDefault(x=>x.IsPoster == false) is not null) ? "20px" : "0px") ; font-weight: bold;">X</span>
                    <input type="hidden" name="BookHoverImgId" value="@Model.BookImages?.FirstOrDefault(x=>x.IsPoster==false)?.Id">
                </div>
                
               
            </div>



            <div class="row"></div>
            <div class="mb-3 col-md-6 pt-3">
                <label asp-for="ImageFiles" class="form-label">Image</label>
                <input asp-for="ImageFiles" class="form-control" placeholder="Image">
                <span asp-validation-for="ImageFiles" class="text-danger"></span>
                <div class="row pt-4">
                    @foreach (BookImage bookimg in Model.BookImages.Where(x=>x.IsPoster==null))
                    {
                        <div class="col-3 pt-3 ml-1" style="position:relative"> 
                            <img width="150px" src="~/uploads/books/@bookimg.Name">
                            <span class="x-button" style="position:absolute; right: 0px;top: 20px;cursor: pointer;color: red;font-size: 20px;font-weight: bold;">X</span>
                            <input type="hidden" name="BookImageIds" value="@bookimg.Id">
                        </div>
                    }
                </div>
            </div>
            <div class="mb-3 col-md-6 pt-3" style="margin-top:10%">
                <div class="row">
                    <div class="col-12">
                        <div style=" display: flex; margin-left: 20%;">
                            <div class="form-check col-md-4 pb-3" style="padding-top: 16px;">
                                <input class="form-check-input" type="checkbox" checked="" data-val="true" data-val-required="The IsAvalible field is required." id="IsAvalible" name="IsAvalible" value="true">
                                <label class="form-check-label" for="IsAvalible">
                                    IsAvalible
                                </label>
                            </div>
                            <div class="form-check col-md-4 pb-3" style="padding-top: 16px;">
                                <input class="form-check-input" type="checkbox" checked="" data-val="true" data-val-required="The IsFeatured field is required." id="IsFeatured" name="IsFeatured" value="true">
                                <label class="form-check-label" for="IsFeatured">
                                    IsFeatured
                                </label>
                            </div>
                            <div class="form-check col-md-4 pb-3" style="padding-top: 16px;">
                                <input class="form-check-input" type="checkbox" checked="" data-val="true" data-val-required="The IsNew field is required." id="IsNew" name="IsNew" value="true">
                                <label class="form-check-label" for="IsNew">
                                    IsNew
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div style="margin-left:16%">
                            <div class="row pt-4 pb-5">
                                <div class="col-md-6">
                                    <label asp-for="AuthorId">Authors</label>
                                    <select asp-for="AuthorId" asp-items="@(new SelectList(ViewBag.Authors,"Id","Name"))">
                                    </select>
                                    <span asp-validation-for="AuthorId" class="text-danger"></span>
                                </div>
                                <div class="col-md-6">
                                    <label asp-for="CategoryId">Categories</label>
                                    <select asp-for="CategoryId" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))">
                                    </select>
                                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>


            </div>

        </div>

        <div class="pb-5" style="display: flex;justify-content: center;margin-top: 55px;">
            <button type="submit" class="btn btn-primary" fdprocessedid="c07dy" style="margin-right: 40px;">
                Update
            </button>
            <button type="submit" class="btn btn-danger" fdprocessedid="3oebx" asp-action="index" asp-controller="book">Cancel</button>
        </div>

    </form>
</div>