PustokImagesUploadTask/Models/Author.cs
using NuGet.Protocol.Core.Types;
using PustokImagesUploadTask.Base;

namespace PustokImagesUploadTask.Models
{
    public class Author : BaseEntity
    {
        public List<Book>? Books { get; set; }
    }
}

PustokImagesUploadTask/Areas/Admin/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using PustokImagesUploadTask.Models;
using System.Reflection;

namespace Pustok.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthorController : Controller
    {
        private readonly AppDbContext _context;

        public AuthorController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Authors.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Author author)
        {
            if (!ModelState.IsValid) return View();

            _context.Authors.Add(author);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            Author author = _context.Authors.FirstOrDefault(x => x.Id == id);

            if (author is null) return View("Error");

            return View(author);
        }

        [HttpPost]
        public IActionResult Update(Author author)
        {
            Author existAuthor = _context.Authors.FirstOrDefault(x => x.Id == author.Id);
            if (existAuthor is null) return View("Error");

            PropertyInfo[] destination = existAuthor.GetType().GetProperties();
            PropertyInfo[] source = author.GetType().GetProperties();

            for (int i = 0; i < destination.Length; i++)
            {
                destination[i].SetValue(existAuthor, source[i].GetValue(author));
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            Author author = _context.Authors.FirstOrDefault(x => x.Id == id);
            if (author is null) return NotFound();
            _context.Authors.Remove(author);
            _context.SaveChanges();
            return Ok();
        }
    }
}

PustokImagesUploadTask/Areas/Admin/Views/Author/Create.cshtml
@model Author


<div class="container-fluid">
    <h1 style="text-align:center">Create Author</h1>

    <form method="post" asp-action="create">
        <div class="mb-3 col-md-3 pt-3 pb-3">
            <label asp-for="Name" class="form-label">FullName</label>
            <input asp-for="Name" class="form-control" placeholder="FullName">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

PustokImagesUploadTask/Areas/Admin/Views/Author/Index.cshtml
@model List<Author>
@{
    int counter = 0;
}

<div class="container">
    <h1 style="text-align:center">Authors</h1>
</div>

<div class="container-fluid">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Id</th>
                <th scope="col">FullName</th>
                <th scope="col">Actions</th>
                <th scope="col"> <a asp-action="create" asp-controller="Author" class="btn btn-success">Create an author</a></th>

            </tr>
        </thead>
        <tbody>
            @foreach (Author author in Model)
            {
                counter++;
                <tr>
                    <th scope="row">@counter</th>
                    <td>@author.Id</td>
                    <td>@author.Name</td>
                    <td>
                        <a asp-action="update" asp-controller="author" asp-route-id="@author.Id" class="btn btn-info">Update</a>
                        <a asp-action="delete" asp-controller="author" asp-route-id="@author.Id" class="btn btn-danger deletebutton">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

PustokImagesUploadTask/Areas/Admin/Views/Author/Update.cshtml
@model Author


<div class="container-fluid">
    <h1 style="text-align:center">Update Author</h1>

    <form method="post" asp-action="update">
                <div class="mb-3 col-md-3 pt-3 pb-3">
                    <label asp-for="Name" class="form-label">FullName</label>
            <input asp-for="Name" class="form-control" placeholder="FullName">
            <span asp-validation-for="Name" class="text-danger"></span>
                </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>